name: keras-ros
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.13
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pip:
        - moviepy
        - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp27-none-linux_x86_64.whl
        - keras==2.0.2
